import type { ColorsMap } from './colors-map';
export declare const lightPalette: {
    "txt-primary": string;
    "txt-primary-invert": string;
    "txt-secondary": string;
    "txt-secondary-invert": string;
    "txt-placeholder": string;
    "accent-primary": string;
    "accent-primary-hover": string;
    "accent-primary-active": string;
    "accent-primary-disabled": string;
    "bg-primary": string;
    "bg-primary-hover": string;
    "bg-primary-active": string;
    "bg-primary-0-5-opacity": string;
    "bg-secondary": string;
    "icons-primary": string;
    "icons-primary-opacity-0-6": string;
    "icons-secondary": string;
    "btn-primary-text": string;
    "btn-disabled-text": string;
    "link-primary": string;
    "link-hover": string;
    "link-active": string;
    "borders-primary": string;
    "borders-secondary": string;
    "borders-strong": string;
    "borders-invert": string;
    "border-active-bottom": string;
    "active-secondary": string;
    "active-secondary-hover": string;
    "active-secondary-active": string;
    tag: string;
    error: string;
    success: string;
    warning: string;
    info: string;
    "light-shadow": string;
};
export declare const defaultPalette: ColorsMap;
