export default [
    {
        "text": "Heading",
        "x": 95,
        "y": 51,
        "fontSize": 50,
        "width": 360,
        "height": 52,
        "align": "center",
        "fontStyle": "bold",
        "fontFamily": "Wayfarer",
        "fill": "#ffff",
        "letterSpacing": 3,
        "lineHeight": 1,
    },
    {
        "fill": "rgb(208, 79, 248)",
        "stroke": "rgb(191, 181, 90)",
        "strokeWidth": 1,
        "shadowOffsetX": -4,
        "shadowOffsetY": -4,
        "shadowBlur": 4,
        "shadowColor": "rgb(240, 255, 245)",
        "shadowOpacity": 1,
        "opacity": 1,
        "text": "Welcome",
        "fontFamily": "Wayfarer",
        "fontSize": 50,
        "letterSpacing": 0,
        "lineHeight": 1,
        "align": "center",
        "fontStyle": "bold",
        "name": "Text",
        "x": 110,
        "y": 155,
        "width": 305,
        "height": 55,
        "rotation": 0,
        "scaleX": 1,
        "scaleY": 1
    },
    {
        "fill": "rgb(248, 114, 230)",
        "stroke": "rgb(254, 6, 237)",
        "strokeWidth": 1,
        "shadowOffsetX": -2,
        "shadowOffsetY": 0,
        "shadowBlur": 44,
        "shadowColor": "rgb(255, 41, 241)",
        "shadowOpacity": 1,
        "opacity": 1,
        "fontFamily": "Thunder",
        "letterSpacing": 2,
        "lineHeight": 2,
        "align": "center",
        "fontStyle": "bold",
        "name": "Text",
        "rotation": 0,
        "scaleX": 1,
        "scaleY": 1,
        "text": "RESPARK",
        "x": 85,
        "y": 117,
        "fontSize": 60,
        "width": 375,
        "height": 120,
    },
    {
        "fill": "rgb(255, 255, 255)",
        "stroke": "rgb(255, 164, 128)",
        "strokeWidth": 1,
        "shadowOffsetX": -4,
        "shadowOffsetY": -4,
        "shadowBlur": 4,
        "shadowColor": "rgb(240, 255, 245)",
        "shadowOpacity": 1,
        "opacity": 1,
        "fontFamily": "Wayfarer",
        "letterSpacing": 0,
        "lineHeight": 1,
        "align": "center",
        "fontStyle": "bold",
        "name": "Text",
        "rotation": 0,
        "scaleX": 1,
        "scaleY": 1,
        "text": "Welcome To Respark",
        "x": 130,
        "y": 110,
        "fontSize": 50,
        "width": 300,
        "height": 160,
    }

]

export const Headings = [{
    "text": "Add a heading",
    "x": 105,
    "y": 110,
    "fontSize": 40,
    "width": 380,
    "fill": "#000",
    "height": 35,
    "fontStyle": 'bold'
},
{
    "text": "Add a subheading",
    "x": 130,
    "y": 165,
    "fontSize": 30,
    "width": 335,
    "fill": "#000",
    "height": 33
},
{
    "text": "Add a body text",
    "x": 185,
    "y": 215,
    "fontSize": 20,
    "width": 190,
    "fill": "#000",
    "height": 30
}]